### ISSUE TITLE
開発環境に関する懸案事項

### ISSUE THREAD

**Issue by ykHakata** [ykHakata/TrainingHackers#1]
開発にあたり、懸案事項を洗い出して行きましょう

**Comment by ykHakata** [comment]
・開発用のサーバー(暫定)
www13429ui.sakura.ne.jp - 133.242.185.203
さくらのVPSを使います、こちらをまっさらにして使いましょう。

**Comment by kazhiramatsu** [comment]
Plackでいきますか？時間なさそうならMojoliciousでも良いです

**Comment by ykHakata** [comment]
PlackでもMojoでも、お任せします！やりやすい方でよろしくお願いします！
