### ISSUE TITLE
出題問題の作成

### ISSUE THREAD

**Issue by kazhiramatsu** [ykHakata/TrainingHackers#4]

**Comment by ykHakata** [comment]
# 出題問題原案

## 1問目: シーザー暗号

## 2問目: パスワード突破

## 3問目: リスティング型パスワード突破

## 4問目: サイトを改竄せよ

## 5問目: 写真が撮られた場所を特定せよ

## 6問目: バイナリファイル解析

## 7問目:

## 8問目:

## 9問目:

## 10問目:

**Comment by ykHakata** [comment]
## 1問目: シーザー暗号

### 問題の概要

```
シーザー暗号を解読する
```

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 2問目: パスワード突破

### 問題の概要

```
答えがJSにかいてある
```

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 3問目: リスティング型パスワード突破

### 問題の概要

```
手元にユーザー名と暗号化されたパスワードの一覧がある。パスワードはシーザー暗号化されている。
```

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 4問目: サイトを改竄せよ

### 問題の概要

```
脆弱性を仕込んだテキストボックスを用意しておく
```

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 5問目: 写真が撮られた場所を特定せよ

### 問題の概要

```
exifに位置情報を仕込んでおく
```

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 6問目: バイナリファイル解析

### 問題の概要

```
バイナリにパスワードが埋め込まれている。それを調べる
```

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 7問目:

### 問題の概要

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 8問目:

### 問題の概要

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 9問目:

### 問題の概要

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)

**Comment by ykHakata** [comment]
## 10問目:

### 問題の概要

### 問題文

### 解答

### ヒント

#### ヒント１

#### ヒント２

#### ヒント３

#### ヒント４

#### ヒント５(答え)
